TUNE=peak
LABEL=mytest-m64
NUMBER=644
NAME=nab_s
SOURCES= nabmd.c sff.c nblist.c prm.c memutil.c molio.c molutil.c \
	 errormsg.c binpos.c rand2.c select_atoms.c reslib.c database.c \
	 traceback.c chirvol.c specrand/specrand.c regex-alpha/regcomp.c \
	 regex-alpha/regerror.c regex-alpha/regexec.c regex-alpha/regfree.c
EXEBASE=nab_s
NEED_MATH=yes
BENCHLANG=C

BASE_DIR         = /usr
BENCH_FLAGS      = -Ispecrand -Iregex-alpha -DNDEBUG -DNOPERFLIB -DNOREDUCE
CC               = $(LLVM_BIN_PATH)/clang -m64
CC_VERSION_OPTION = -v
CLD              = $(LLVM_BIN_PATH)/clang -m64
COPTIMIZE        = -Ofast -mavx
CXX              = $(LLVM_BIN_PATH)/clang++ -m64
CXXOPTIMIZE      = -O3 -mavx
CXX_VERSION_OPTION = -v
EXTRA_FFLAGS     = -fplugin=$(DRAGONEGG_PATH)/dragonegg.so
EXTRA_FLIBS      = -fopenmp=libomp -lgfortran -lm
EXTRA_LIBS       = -fopenmp=libomp -L$(OPENMP_LIB_PATH) -lomp
EXTRA_OPTIMIZE   = -DSPEC_OPENMP -fopenmp -Wno-return-type -DUSE_OPENMP -I $(OPENMP_DIR)/common/include
EXTRA_PORTABILITY = -DSPEC_LP64
FC               = $(FORTRAN_COMP) -m64
FC_VERSION_OPTION = -v
FLD              = $(LLVM_BIN_PATH)/clang -m64
FOPTIMIZE        = -Ofast -mavx -funroll-loops -fno-stack-arrays
FORTRAN_COMP     = $(GFORTRAN_DIR)/gfortran
LLVM_BIN_PATH    = /usr//bin
LLVM_INCLUDE_PATH = /usr//include
LLVM_LIB_PATH    = /usr//lib
LLVM_PATH        = /usr
LLVM_ROOT_PATH   = /usr/
OPENMP_DIR       = /usr/lib/libomp_oss/exports
OPENMP_LIB_PATH  = /usr/lib/libomp_oss/exports/lin_32e/lib
OS               = unix
absolutely_no_locking = 0
abstol           = 
action           = build
allow_label_override = 0
backup_config    = 1
baseexe          = nab_s
basepeak         = 0
benchdir         = benchspec
benchmark        = 644.nab_s
binary           = 
bindir           = exe
builddir         = build
bundleaction     = 
bundlename       = 
calctol          = 1
changedhash      = 0
check_version    = 0
clean_between_builds = no
command_add_redirect = 0
commanderrfile   = speccmds.err
commandexe       = nab_s_peak.mytest-m64
commandfile      = speccmds.cmd
commandoutfile   = speccmds.out
commandstdoutfile = speccmds.stdout
comparedir       = compare
compareerrfile   = compare.err
comparefile      = compare.cmd
compareoutfile   = compare.out
comparestdoutfile = compare.stdout
compile_error    = 0
compwhite        = 
configdir        = config
configfile       = clang
configpath       = /home/theo/2017_install/config/clang.cfg
copies           = 1
current_range    = 
datadir          = data
default_size     = ref
default_submit   = $command
delay            = 0
deletebinaries   = 0
deletework       = 0
dependent_workloads = 0
device           = 
difflines        = 10
dirprot          = 511
discard_power_samples = 0
enable_monitor   = 1
endian           = 12345678
env_vars         = 0
expand_notes     = 0
expid            = 
exthash_bits     = 256
failflags        = 0
fake             = 0
feedback         = 1
flag_url_base    = https://www.spec.org/auto/cpu2017/Docs/benchmarks/flags/
floatcompare     = 
force_monitor    = 0
from_runcpu      = 2
fw_bios          = 
hostname         = hammerhead
http_proxy       = 
http_timeout     = 30
hw_avail         = 
hw_cpu_max_mhz   = 
hw_cpu_name      = AMD Ryzen Threadripper 1950X 16-Core
hw_cpu_nominal_mhz = 
hw_disk          = 358 GB  add more disk info here
hw_memory001     = 31.220 GB fixme: If using DDR3, format is:
hw_memory002     = 'N GB (M x N GB nRxn PCn-nnnnnR-n, ECC)'
hw_model         = 
hw_nchips        = 1
hw_ncores        = 
hw_ncpuorder     = 
hw_nthreadspercore = 
hw_ocache        = 
hw_other         = 
hw_pcache        = 
hw_scache        = 
hw_tcache        = 
hw_vendor        = My Corporation
idle_current_range = 
idledelay        = 10
idleduration     = 60
ignore_errors    = 1
ignore_sigint    = 0
ignorecase       = 
info_wrap_columns = 50
inputdir         = input
inputgenerrfile  = inputgen.err
inputgenfile     = inputgen.cmd
inputgenoutfile  = inputgen.out
inputgenstdoutfile = inputgen.stdout
iteration        = -1
iterations       = 1
keeptmp          = 0
label            = mytest-m64
license_num      = nnn (Your SPEC license number)
line_width       = 1020
link_input_files = 1
locking          = 1
log              = CPU2017
log_line_width   = 1020
log_timestamp    = 0
logfile          = /home/theo/2017_install/tmp/CPU2017.013/templogs/preenv.fpspeed.013.1
logname          = /home/theo/2017_install/tmp/CPU2017.013/templogs/preenv.fpspeed.013.1
lognum           = 013.1
mail_reports     = all
mailcompress     = 0
mailmethod       = smtp
mailport         = 25
mailserver       = 127.0.0.1
mailto           = 
make             = specmake
make_no_clobber  = 0
makefile_template = Makefile.YYYtArGeTYYYspec
makeflags        = --jobs=16
max_average_uncertainty = 1
max_hum_limit    = 0
max_report_runs  = 3
max_unknown_uncertainty = 1
mean_anyway      = 1
meter_connect_timeout = 30
meter_errors_default = 5
meter_errors_percentage = 5
min_report_runs  = 2
min_temp_limit   = 20
minimize_builddirs = 0
minimize_rundirs = 0
name             = nab_s
nansupport       = 
need_math        = yes
no_input_handler = close
no_monitor       = 
noratios         = 0
note_preenv      = 1
notes_plat_sysinfo_000 =  Sysinfo program /home/theo/2017_install/bin/sysinfo
notes_plat_sysinfo_005 =  Rev: r5797 of 2017-06-14 96c45e4568ad54c135fd618bcc091c0f
notes_plat_sysinfo_010 =  running on hammerhead Thu Mar 10 16:32:20 2022
notes_plat_sysinfo_015 = 
notes_plat_sysinfo_020 =  SUT (System Under Test) info as seen by some common utilities.
notes_plat_sysinfo_025 =  For more information on this section, see
notes_plat_sysinfo_030 =     https://www.spec.org/cpu2017/Docs/config.html\#sysinfo
notes_plat_sysinfo_035 = 
notes_plat_sysinfo_040 =  From /proc/cpuinfo
notes_plat_sysinfo_045 =     model name : AMD Ryzen Threadripper 1950X 16-Core Processor
notes_plat_sysinfo_050 =        1  "physical id"s (chips)
notes_plat_sysinfo_055 =        32 "processors"
notes_plat_sysinfo_060 =     cores, siblings (Caution: counting these is hw and system dependent. The following
notes_plat_sysinfo_065 =     excerpts from /proc/cpuinfo might not be reliable.  Use with caution.)
notes_plat_sysinfo_070 =        cpu cores : 16
notes_plat_sysinfo_075 =        siblings  : 32
notes_plat_sysinfo_080 =        physical 0: cores 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
notes_plat_sysinfo_085 = 
notes_plat_sysinfo_090 =  From lscpu:
notes_plat_sysinfo_095 =       Architecture:                    x86_64
notes_plat_sysinfo_100 =       CPU op-mode(s):                  32-bit, 64-bit
notes_plat_sysinfo_105 =       Address sizes:                   43 bits physical, 48 bits virtual
notes_plat_sysinfo_110 =       Byte Order:                      Little Endian
notes_plat_sysinfo_115 =       CPU(s):                          32
notes_plat_sysinfo_120 =       On-line CPU(s) list:             0-31
notes_plat_sysinfo_125 =       Vendor ID:                       AuthenticAMD
notes_plat_sysinfo_130 =       Model name:                      AMD Ryzen Threadripper 1950X 16-Core Processor
notes_plat_sysinfo_135 =       CPU family:                      23
notes_plat_sysinfo_140 =       Model:                           1
notes_plat_sysinfo_145 =       Thread(s) per core:              2
notes_plat_sysinfo_150 =       Core(s) per socket:              16
notes_plat_sysinfo_155 =       Socket(s):                       1
notes_plat_sysinfo_160 =       Stepping:                        1
notes_plat_sysinfo_165 =       Frequency boost:                 enabled
notes_plat_sysinfo_170 =       CPU max MHz:                     3400.0000
notes_plat_sysinfo_175 =       CPU min MHz:                     2200.0000
notes_plat_sysinfo_180 =       BogoMIPS:                        6789.29
notes_plat_sysinfo_185 =       Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr
notes_plat_sysinfo_190 =       pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt
notes_plat_sysinfo_195 =       pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm
notes_plat_sysinfo_200 =       aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes
notes_plat_sysinfo_205 =       xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a
notes_plat_sysinfo_210 =       misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext
notes_plat_sysinfo_215 =       perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2
notes_plat_sysinfo_220 =       rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf
notes_plat_sysinfo_225 =       xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid
notes_plat_sysinfo_230 =       decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov
notes_plat_sysinfo_235 =       succor smca sme sev
notes_plat_sysinfo_240 =       Virtualization:                  AMD-V
notes_plat_sysinfo_245 =       L1d cache:                       512 KiB (16 instances)
notes_plat_sysinfo_250 =       L1i cache:                       1 MiB (16 instances)
notes_plat_sysinfo_255 =       L2 cache:                        8 MiB (16 instances)
notes_plat_sysinfo_260 =       L3 cache:                        32 MiB (4 instances)
notes_plat_sysinfo_265 =       NUMA node(s):                    1
notes_plat_sysinfo_270 =       NUMA node0 CPU(s):               0-31
notes_plat_sysinfo_275 =       Vulnerability Itlb multihit:     Not affected
notes_plat_sysinfo_280 =       Vulnerability L1tf:              Not affected
notes_plat_sysinfo_285 =       Vulnerability Mds:               Not affected
notes_plat_sysinfo_290 =       Vulnerability Meltdown:          Not affected
notes_plat_sysinfo_295 =       Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via
notes_plat_sysinfo_300 =       prctl
notes_plat_sysinfo_305 =       Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
notes_plat_sysinfo_310 =       pointer sanitization
notes_plat_sysinfo_315 =       Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional,
notes_plat_sysinfo_320 =       STIBP disabled, RSB filling
notes_plat_sysinfo_325 =       Vulnerability Srbds:             Not affected
notes_plat_sysinfo_330 =       Vulnerability Tsx async abort:   Not affected
notes_plat_sysinfo_335 = 
notes_plat_sysinfo_340 =  /proc/cpuinfo cache data
notes_plat_sysinfo_345 =     cache size : 512 KB
notes_plat_sysinfo_350 = 
notes_plat_sysinfo_355 =  From numactl --hardware  WARNING: a numactl 'node' might or might not correspond to a
notes_plat_sysinfo_360 =  physical chip.
notes_plat_sysinfo_365 =    available: 1 nodes (0)
notes_plat_sysinfo_370 =    node 0 cpus: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
notes_plat_sysinfo_375 =    28 29 30 31
notes_plat_sysinfo_380 =    node 0 size: 31968 MB
notes_plat_sysinfo_385 =    node 0 free: 13893 MB
notes_plat_sysinfo_390 =    node distances:
notes_plat_sysinfo_395 =    node   0
notes_plat_sysinfo_400 =      0:  10
notes_plat_sysinfo_405 = 
notes_plat_sysinfo_410 =  From /proc/meminfo
notes_plat_sysinfo_415 =     MemTotal:       32736208 kB
notes_plat_sysinfo_420 =     HugePages_Total:       0
notes_plat_sysinfo_425 =     Hugepagesize:       2048 kB
notes_plat_sysinfo_430 = 
notes_plat_sysinfo_435 =  /usr/bin/lsb_release -d
notes_plat_sysinfo_440 =     Arch Linux
notes_plat_sysinfo_445 = 
notes_plat_sysinfo_450 =  From /etc/*release* /etc/*version*
notes_plat_sysinfo_455 =     os-release:
notes_plat_sysinfo_460 =        NAME="Arch Linux"
notes_plat_sysinfo_465 =        PRETTY_NAME="Arch Linux"
notes_plat_sysinfo_470 =        ID=arch
notes_plat_sysinfo_475 =        BUILD_ID=rolling
notes_plat_sysinfo_480 =        ANSI_COLOR="38;2;23;147;209"
notes_plat_sysinfo_485 =        HOME_URL="https://archlinux.org/"
notes_plat_sysinfo_490 =        DOCUMENTATION_URL="https://wiki.archlinux.org/"
notes_plat_sysinfo_495 =        SUPPORT_URL="https://bbs.archlinux.org/"
notes_plat_sysinfo_500 = 
notes_plat_sysinfo_505 =  uname -a:
notes_plat_sysinfo_510 =     Linux hammerhead 5.16.13-arch1-1 \#1 SMP PREEMPT Tue, 08 Mar 2022 20:07:36 +0000 x86_64
notes_plat_sysinfo_515 =     GNU/Linux
notes_plat_sysinfo_520 = 
notes_plat_sysinfo_525 = 
notes_plat_sysinfo_530 =  SPEC is set to: /home/theo/2017_install
notes_plat_sysinfo_535 =     Filesystem     Type  Size  Used Avail Use% Mounted on
notes_plat_sysinfo_540 =     /dev/nvme0n1p5 ext4  358G  285G   55G  84% /home
notes_plat_sysinfo_545 = 
notes_plat_sysinfo_550 =  Additional information from dmidecode follows.  WARNING: Use caution when you interpret
notes_plat_sysinfo_555 =  this section. The 'dmidecode' program reads system data which is "intended to allow
notes_plat_sysinfo_560 =  hardware to be accurately determined", but the intent may not be met, as there are
notes_plat_sysinfo_565 =  frequent changes to hardware, firmware, and the "DMTF SMBIOS" standard.
notes_plat_sysinfo_570 = 
notes_plat_sysinfo_575 =  (End of data from sysinfo program)
notes_wrap_columns = 0
notes_wrap_indent =   
num              = 644
obiwan           = 
oldhash          = 
os_exe_ext       = 
output_format    = txt,html,cfg,pdf,csv
output_root      = 
outputdir        = output
parallel_test    = 0
parallel_test_submit = 0
parallel_test_workloads = 
path             = /home/theo/2017_install/benchspec/CPU/644.nab_s
plain_train      = 1
platform         = 
power            = 0
preENV_GOMP_CPU_AFFINITY = 0-%{cputhreads}
preENV_LD_LIBRARY_PATH = /usr//lib:/usr/lib/libomp_oss/exports/lin_32e/lib
preENV_LIBRARY_PATH = /usr//lib:/usr/lib/libomp_oss/exports/lin_32e/lib
preENV_OMP_STACKSIZE = 128M
preENV_OMP_THREAD_LIMIT = %{cputhreads}
preENV_PATH      = /usr//bin:%{ENV_PATH}
preenv           = 0
prefix           = 
prepared_by      = theo  (is never output, only tags rawfile)
ranks            = 1
rawhash_bits     = 256
rebuild          = 0
reftime          = reftime
reltol           = 0.01
reportable       = 0
resultdir        = result
review           = 0
run              = all
runcpu           = /home/theo/2017_install/bin/harness/runcpu --define build_ncpus=16 --configfile clang --noreportable --action build --noreportable --nopower --runmode speed --tune base:peak --size refspeed 619.lbm_s 638.imagick_s 644.nab_s 996.specrand_fs --nopreenv --note-preenv --logfile /home/theo/2017_install/tmp/CPU2017.013/templogs/preenv.fpspeed.013.1 --lognum 013.1 --from_runcpu 2
rundir           = run
runmode          = speed
safe_eval        = 1
save_build_files = 
section_specifier_fatal = 1
setprocgroup     = 1
setup_error      = 0
sigint           = 2
size             = refspeed
size_class       = ref
skipabstol       = 
skipobiwan       = 
skipreltol       = 2
skiptol          = 
smarttune        = peak
specdiff         = specdiff
specrun          = specinvoke
srcalt           = 
srcdir           = src
srcsource        = /home/theo/2017_install/benchspec/CPU/544.nab_r/src
stagger          = 10
strict_rundir_verify = 1
sw_avail         = 
sw_base_ptrsize  = 64-bit
sw_compiler001   = C/C++: Version 3.9.0 of Clang, the
sw_compiler002   = LLVM Compiler Infrastructure
sw_compiler003   = Fortran: Version 4.8.2 of GCC, the
sw_compiler004   = GNU Compiler Collection
sw_compiler005   = DragonEgg: Version 3.5.2, the
sw_compiler006   = LLVM Compiler Infrastructure
sw_file          = ext4
sw_os001         = Arch Linux
sw_os002         = 5.16.13-arch1-1
sw_other         = 
sw_peak_ptrsize  = 64-bit
sw_state         = Run level N (add definition here)
sysinfo_hash_bits = 256
sysinfo_program  = specperl /home/theo/2017_install/bin/sysinfo
sysinfo_program_hash = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
table            = 1
teeout           = 0
test_date        = Mar-2022
test_sponsor     = My Corporation
tester           = My Corporation
threads          = 8
top              = /home/theo/2017_install
train_single_thread = 0
train_with       = train
tune             = peak
uid              = 1000
unbuffer         = 1
uncertainty_exception = 5
update           = 0
update_url       = http://www.spec.org/auto/cpu2017/updates/
use_submit_for_compare = 0
use_submit_for_speed = 0
username         = theo
verbose          = 5
verify_binaries  = 1
version          = 0.903000
version_url      = http://www.spec.org/auto/cpu2017/devel_version
voltage_range    = 
worklist         = list
OUTPUT_RMFILES   = aminos.out gcn4dna.out
